# Generated by Django 3.1.4 on 2022-05-18 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rental_name', models.TextField()),
                ('name', models.TextField(null=True)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('previous_reservation', models.TextField(null=True)),
                ('rental_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.rental')),
            ],
        ),
    ]
